// <auto-generated/>
#pragma warning disable CS0618
using Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByStatus;
using Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByTags;
using Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet
{
    /// <summary>
    /// Builds and executes requests for operations under \pet
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The findByStatus property</summary>
        public global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByStatus.FindByStatusRequestBuilder FindByStatus
        {
            get => new global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByStatus.FindByStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The findByTags property</summary>
        public global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByTags.FindByTagsRequestBuilder FindByTags
        {
            get => new global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.FindByTags.FindByTagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.pet.item collection</summary>
        /// <param name="position">ID of pet to return</param>
        /// <returns>A <see cref="global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.Item.WithPetItemRequestBuilder"/></returns>
        public global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.Item.WithPetItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("petId", position);
                return new global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.Item.WithPetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.PetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ktt.Resilience.Clients.Kiota.HttpClients.PetStore.Pet.PetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/pet", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
