// <auto-generated/>
#pragma warning disable CS0618
using Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.FiveZeroZero;
using Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.RandomNamespace;
using Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.TwoZeroZero;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Ktt.Resilience.KiotaClients.HttpClients.HttpStatus
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HttpStatusClient : BaseRequestBuilder
    {
        /// <summary>The FiveZeroZero property</summary>
        public global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.FiveZeroZero.FiveZeroZeroRequestBuilder FiveZeroZero
        {
            get => new global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.FiveZeroZero.FiveZeroZeroRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The random property</summary>
        public global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.RandomNamespace.RandomRequestBuilder Random
        {
            get => new global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.RandomNamespace.RandomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TwoZeroZero property</summary>
        public global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.TwoZeroZero.TwoZeroZeroRequestBuilder TwoZeroZero
        {
            get => new global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.TwoZeroZero.TwoZeroZeroRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Ktt.Resilience.KiotaClients.HttpClients.HttpStatus.HttpStatusClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HttpStatusClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
