<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.38" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ktt.RomanNumerals\Ktt.RomanNumerals.csproj" />
  </ItemGroup>

</Project>
